apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rapid7exporter.fullname" . }}-config
  labels:
    app: {{ include "rapid7exporter.name" . }}
data:
  config.yaml: |-
{{ .Values.config | indent 4 }}
