replicaCount: 1

image:
  repository: mtrb/rapid7exporter
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

# Configuration for rapid7exporter (this will be loaded as a ConfigMap)
config: |-
  retention: 230
  latestScan: true
  updatePeriod: 1440
  loglevel: info
  severities:
    - CRITICAL
    - HIGH
    - MEDIUM
    - LOW
  dummyApps:
    - id: "dummy-001"
      name: "pf-haptoatlas"
  renamePatterns:
    - pattern: ".*mystudies.*"
      newName: "mystudies"
    - pattern: ".*alfresco.*"
      newName: "alfresco"
    - pattern: "vivax.*"
      newName: "roma-vivax"
    - pattern: "spotmalaria.*"
      newName: "roma-spotmalaria"
    - pattern: "vobs.*"
      newName: "roma-vobs"
    - pattern: "^genre.*"
      newName: "roma-genre"
    - pattern: ".*glad.*"
      newName: "glad"
  envPatterns:
    - pattern: "^.*-staging.*"
      env: "staging"
    - pattern: "^.*-dev.*"
      env: "dev"
    - pattern: "^.*-uat.*"
      env: "uat"
    - pattern: "^.*-test.*"
      env: "test"
    - pattern: ".*"
      env: "production"
  groupPatterns:
    - pattern: "^.*vivax.*"
      group: "roma"
    - pattern: "^.*vobs.*"
      group: "roma"
    - pattern: "^.*genre.*"
      group: "roma"
    - pattern: "^.*spotmalaria.*"
      group: "roma"
    - pattern: ".*alfres.*"
      group: "alfresco"

# Security and Pod settings
podSecurityContext:
  runAsUser: 1000
  fsGroup: 2000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false

serviceMonitor:
  enabled: true
  interval: 10m
  scrapeTimeout: 1m


# Cache volume configuration (emptyDir)
cacheVolume:
  emptyDir: {}

# Service account settings (if you want to create a dedicated one)
serviceAccount:
  create: false
  name: ""

# Additional configuration to override command-line flags if desired.
# These values are passed into the container as environment variables.
configOverrides: {}
